# Generated by Django 5.2.6 on 2025-09-13 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Zaplanowana'), ('completed', 'Zakończona'), ('cancelled', 'Anulowana'), ('no_show', 'Niestawiennictwo')], default='scheduled', max_length=15)),
                ('reason', models.CharField(help_text='Powód wizyty', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notatki z wizyty')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
