# Generated by Django 5.2.7 on 2025-10-29 12:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_recurring",
            field=models.BooleanField(
                default=False, help_text="Czy wizyta jest częścią serii"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="parent_appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Pierwsza wizyta w serii (dla śledzenia całej serii)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_instances",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True, help_text="Data końca powtarzania serii", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("none", "Brak powtórzeń"),
                    ("weekly", "Co tydzień"),
                    ("biweekly", "Co 2 tygodnie"),
                    ("monthly", "Co miesiąc"),
                ],
                default="none",
                help_text="Wzorzec powtarzania",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Notatki z wizyty (dla lekarza)", null=True
            ),
        ),
    ]
