# Generated by Django 5.2.7 on 2025-10-30 07:04

import appointments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_is_recurring_and_more"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=appointments.models.appointment_attachment_path,
                        verbose_name="Plik",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Zdjęcie"),
                            ("document", "Dokument"),
                            ("test_result", "Wynik badania"),
                            ("other", "Inne"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Typ pliku",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Opcjonalny opis załącznika",
                        verbose_name="Opis",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data uploadu"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        default=0, verbose_name="Rozmiar pliku (bajty)"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="appointments.appointment",
                        verbose_name="Wizyta",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctors.doctor",
                        verbose_name="Dodane przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Załącznik do wizyty",
                "verbose_name_plural": "Załączniki do wizyt",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
