# Generated by Django 5.2.7 on 2025-10-30 07:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointmentattachment"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa szablonu wyświetlana na liście",
                        max_length=200,
                        verbose_name="Nazwa szablonu",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Krótki opis przeznaczenia szablonu",
                        verbose_name="Opis",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Treść szablonu notatki (HTML)",
                        verbose_name="Treść szablonu",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consultation", "Konsultacja"),
                            ("checkup", "Kontrola"),
                            ("test_results", "Wyniki badań"),
                            ("medication", "Zmiana leczenia"),
                            ("diet", "Dieta"),
                            ("complication", "Powikłanie"),
                            ("education", "Edukacja pacjenta"),
                            ("other", "Inne"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Kategoria",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Czy szablon jest dostępny do użycia",
                        verbose_name="Aktywny",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aktualizacji"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to="doctors.doctor",
                        verbose_name="Utworzony przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Szablon notatki",
                "verbose_name_plural": "Szablony notatek",
                "ordering": ["category", "name"],
            },
        ),
    ]
