# Generated by Django 5.2.7 on 2025-10-30 07:30

from django.db import migrations


def create_default_templates(apps, schema_editor):
    """Create default note templates for common diabetes clinic cases"""
    NoteTemplate = apps.get_model('appointments', 'NoteTemplate')

    templates = [
        {
            'name': 'Konsultacja diabetologiczna - pierwsza wizyta',
            'category': 'consultation',
            'description': 'Szablon dla pierwszej wizyty diabetologicznej nowego pacjenta',
            'content': '''<h3><strong>Wywiad chorobowy</strong></h3>
<ul>
<li>Rozpoznanie cukrzycy: rok, okoliczności</li>
<li>Typ cukrzycy:</li>
<li>Dotychczasowe leczenie:</li>
<li>Dotychczasowa kontrola glikemii (HbA1c):</li>
</ul>

<h3><strong>Współistniejące choroby</strong></h3>
<ul>
<li>Nadciśnienie tętnicze:</li>
<li>Zaburzenia lipidowe:</li>
<li>Choroby serca:</li>
<li>Inne:</li>
</ul>

<h3><strong>Powikłania cukrzycy</strong></h3>
<ul>
<li>Retinopatia:</li>
<li>Nefropatia:</li>
<li>Neuropatia:</li>
<li>Stopa cukrzycowa:</li>
</ul>

<h3><strong>Badanie przedmiotowe</strong></h3>
<p>Wzrost: ___ cm | Waga: ___ kg | BMI: ___</p>
<p>RR: ___ / ___ mmHg | Tętno: ___ /min</p>
<p>Glikemia: ___ mg/dl</p>

<h3><strong>Zalecenia</strong></h3>
<ul>
<li>Modyfikacja stylu życia (dieta, aktywność fizyczna)</li>
<li>Leczenie farmakologiczne:</li>
<li>Zalecane badania:</li>
<li>Termin kolejnej wizyty:</li>
</ul>'''
        },
        {
            'name': 'Kontrola ambulatoryjna',
            'category': 'checkup',
            'description': 'Rutynowa kontrola pacjenta z cukrzycą',
            'content': '''<h3><strong>Samopoczucie</strong></h3>
<p>Stan ogólny pacjenta:</p>

<h3><strong>Parametry</strong></h3>
<table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse; width: 100%;">
<tbody>
<tr>
<td><strong>Waga</strong></td>
<td>___ kg</td>
</tr>
<tr>
<td><strong>RR</strong></td>
<td>___ / ___ mmHg</td>
</tr>
<tr>
<td><strong>Glikemia</strong></td>
<td>___ mg/dl</td>
</tr>
</tbody>
</table>

<h3><strong>Samokontrola glikemii</strong></h3>
<p>Zakres pomiarów domowych: ___-___ mg/dl</p>
<p>Hipoglikemie: TAK / NIE</p>

<h3><strong>Przestrzeganie zaleceń</strong></h3>
<ul>
<li>Dieta:</li>
<li>Aktywność fizyczna:</li>
<li>Przyjmowanie leków:</li>
</ul>

<h3><strong>Zalecenia</strong></h3>
<p>Kontynuacja dotychczasowego leczenia / modyfikacja:</p>
<p>Kolejna wizyta:</p>'''
        },
        {
            'name': 'Omówienie wyników badań',
            'category': 'test_results',
            'description': 'Szablon do dokumentowania i omawiania wyników badań laboratoryjnych',
            'content': '''<h3><strong>Wyniki badań laboratoryjnych</strong></h3>
<table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse; width: 100%;">
<thead>
<tr>
<th>Badanie</th>
<th>Wynik</th>
<th>Norma</th>
<th>Komentarz</th>
</tr>
</thead>
<tbody>
<tr>
<td>HbA1c</td>
<td>___ %</td>
<td>&lt;7%</td>
<td></td>
</tr>
<tr>
<td>Glukoza na czczo</td>
<td>___ mg/dl</td>
<td>70-100 mg/dl</td>
<td></td>
</tr>
<tr>
<td>Cholesterol całkowity</td>
<td>___ mg/dl</td>
<td>&lt;190 mg/dl</td>
<td></td>
</tr>
<tr>
<td>LDL</td>
<td>___ mg/dl</td>
<td>&lt;100 mg/dl</td>
<td></td>
</tr>
<tr>
<td>HDL</td>
<td>___ mg/dl</td>
<td>&gt;40 mg/dl (M), &gt;50 mg/dl (K)</td>
<td></td>
</tr>
<tr>
<td>Triglicerydy</td>
<td>___ mg/dl</td>
<td>&lt;150 mg/dl</td>
<td></td>
</tr>
<tr>
<td>Kreatynina</td>
<td>___ mg/dl</td>
<td>0.6-1.2 mg/dl</td>
<td></td>
</tr>
<tr>
<td>eGFR</td>
<td>___ ml/min</td>
<td>&gt;90 ml/min</td>
<td></td>
</tr>
</tbody>
</table>

<h3><strong>Interpretacja</strong></h3>
<p>Kontrola metaboliczna:</p>
<p>Funkcja nerek:</p>
<p>Profil lipidowy:</p>

<h3><strong>Dalsze postępowanie</strong></h3>
<ul>
<li>Modyfikacja leczenia (jeśli wskazana):</li>
<li>Zalecane kolejne badania:</li>
</ul>'''
        },
        {
            'name': 'Zmiana leczenia',
            'category': 'medication',
            'description': 'Dokumentacja zmiany terapii',
            'content': '''<h3><strong>Przyczyna zmiany leczenia</strong></h3>
<p>☐ Niedostateczna kontrola glikemii<br>
☐ Działania niepożądane<br>
☐ Progresja choroby<br>
☐ Inne:</p>

<h3><strong>Dotychczasowe leczenie</strong></h3>
<p>Leki:</p>
<ul>
<li></li>
</ul>

<h3><strong>Nowe leczenie</strong></h3>
<p>Leki:</p>
<ul>
<li></li>
</ul>

<h3><strong>Edukacja pacjenta</strong></h3>
<ul>
<li>Sposób przyjmowania:</li>
<li>Możliwe działania niepożądane:</li>
<li>Postępowanie w przypadku hipoglikemii:</li>
</ul>

<h3><strong>Plan kontroli</strong></h3>
<p>Samokontrola glikemii:</p>
<p>Kolejna wizyta za:</p>
<p>Zalecone badania przed kolejną wizytą:</p>'''
        },
        {
            'name': 'Konsultacja dietetyczna',
            'category': 'diet',
            'description': 'Zalecenia żywieniowe dla pacjenta z cukrzycą',
            'content': '''<h3><strong>Ocena dotychczasowego żywienia</strong></h3>
<p>Liczba posiłków dziennie:</p>
<p>Główne problemy:</p>

<h3><strong>Zalecenia dietetyczne</strong></h3>
<h4>Ogólne zasady</h4>
<ul>
<li>Regularne posiłki (4-5 dziennie)</li>
<li>Kontrola wielkości porcji</li>
<li>Ograniczenie cukrów prostych</li>
<li>Zwiększenie spożycia błonnika</li>
</ul>

<h4>Produkty zalecane</h4>
<ul>
<li>Warzywa nieograniczenie (szczególnie zielone)</li>
<li>Owoce (2-3 porcje dziennie, unikać soków)</li>
<li>Pełnoziarniste produkty zbożowe</li>
<li>Chude mięso, ryby</li>
<li>Produkty mleczne naturalne, niskokaloryczne</li>
</ul>

<h4>Produkty ograniczone/unikane</h4>
<ul>
<li><span style="color:#e74c3c;"><strong>Słodycze, ciasta, cukier</strong></span></li>
<li><span style="color:#e74c3c;"><strong>Słodkie napoje</strong></span></li>
<li>Tłuste mięso, wędliny</li>
<li>Fast food</li>
<li>Alkohol</li>
</ul>

<h3><strong>Przykładowy jadłospis</strong></h3>
<p>Śniadanie:<br>
II śniadanie:<br>
Obiad:<br>
Podwieczorek:<br>
Kolacja:</p>

<h3><strong>Zalecenia dotyczące aktywności fizycznej</strong></h3>
<p>Typ aktywności:<br>
Częstotliwość:<br>
Czas trwania:</p>'''
        },
        {
            'name': 'Hipoglikemia - interwencja',
            'category': 'complication',
            'description': 'Dokumentacja epizodu hipoglikemii',
            'content': '''<h3><strong>Okoliczności wystąpienia</strong></h3>
<p>Data i godzina:<br>
Wartość glikemii: ___ mg/dl<br>
Miejsce (dom/praca/inne):</p>

<h3><strong>Objawy</strong></h3>
<ul>
<li>☐ Drżenie, pocenie się</li>
<li>☐ Kołatanie serca</li>
<li>☐ Głód</li>
<li>☐ Osłabienie</li>
<li>☐ Zaburzenia koncentracji</li>
<li>☐ Zaburzenia świadomości</li>
<li>☐ Inne:</li>
</ul>

<h3><strong>Postępowanie</strong></h3>
<p>Sposób wyrównania hipoglikemii:<br>
Glikemia po interwencji: ___ mg/dl</p>

<h3><strong>Możliwe przyczyny</strong></h3>
<ul>
<li>☐ Pominięty posiłek</li>
<li>☐ Zwiększona aktywność fizyczna</li>
<li>☐ Błąd w dawkowaniu leku</li>
<li>☐ Alkohol</li>
<li>☐ Inne:</li>
</ul>

<h3><strong>Edukacja i zalecenia</strong></h3>
<p>Modyfikacja leczenia (jeśli wskazana):<br>
Zalecenia dla pacjenta:<br>
☐ Zawsze nosić przy sobie szybko wchłanialne węglowodany<br>
☐ Informować otoczenie o cukrzycy<br>
☐ Nosić identyfikator cukrzyka</p>'''
        },
        {
            'name': 'Edukacja pacjenta',
            'category': 'education',
            'description': 'Dokumentacja sesji edukacyjnej',
            'content': '''<h3><strong>Temat edukacji</strong></h3>
<p>☐ Samokontrola glikemii<br>
☐ Technika iniekcji insuliny<br>
☐ Stosowanie pompy insulinowej<br>
☐ Rozpoznawanie i postępowanie w hipoglikemii<br>
☐ Dieta<br>
☐ Aktywność fizyczna<br>
☐ Pielęgnacja stóp<br>
☐ Inne:</p>

<h3><strong>Omówione zagadnienia</strong></h3>
<ul>
<li></li>
</ul>

<h3><strong>Materiały edukacyjne</strong></h3>
<p>Przekazane materiały:</p>

<h3><strong>Ocena zrozumienia</strong></h3>
<p>Poziom zrozumienia przekazanych informacji:<br>
☐ Bardzo dobry<br>
☐ Dobry<br>
☐ Wymaga ponowienia</p>

<h3><strong>Demonstracja praktyczna</strong></h3>
<p>Pacjent zademonstrował umiejętność:<br>
☐ Prawidłowo<br>
☐ Wymaga ćwiczenia</p>

<h3><strong>Plan dalszej edukacji</strong></h3>
<p>Tematy do omówienia na kolejnej wizycie:</p>'''
        },
    ]

    for template_data in templates:
        NoteTemplate.objects.create(**template_data)


def remove_default_templates(apps, schema_editor):
    """Remove default templates on migration rollback"""
    NoteTemplate = apps.get_model('appointments', 'NoteTemplate')
    # Delete only the default templates (those without created_by)
    NoteTemplate.objects.filter(created_by__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_notetemplate"),
    ]

    operations = [
        migrations.RunPython(create_default_templates, remove_default_templates),
    ]
