# Generated by Django 5.2.5 on 2025-10-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_create_default_templates"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiabetesPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pregnancies",
                    models.PositiveIntegerField(
                        help_text="Liczba ciąż (0 dla mężczyzn)",
                        verbose_name="Liczba ciąż",
                    ),
                ),
                (
                    "glucose",
                    models.FloatField(
                        help_text="Poziom glukozy we krwi (mg/dL)",
                        verbose_name="Poziom glukozy",
                    ),
                ),
                (
                    "blood_pressure",
                    models.FloatField(
                        help_text="Skurczowe ciśnienie krwi (mm Hg)",
                        verbose_name="Ciśnienie krwi",
                    ),
                ),
                (
                    "skin_thickness",
                    models.FloatField(
                        help_text="Grubość fałdu skórnego tricepsa (mm)",
                        verbose_name="Grubość fałdu skórnego",
                    ),
                ),
                (
                    "insulin",
                    models.FloatField(
                        help_text="Insulina w surowicy (μU/ml)",
                        verbose_name="Poziom insuliny",
                    ),
                ),
                (
                    "bmi",
                    models.FloatField(
                        help_text="Wskaźnik masy ciała (kg/m²)", verbose_name="BMI"
                    ),
                ),
                (
                    "diabetes_pedigree",
                    models.FloatField(
                        help_text="Funkcja rodowodu cukrzycy (0.0 - 2.5)",
                        verbose_name="Funkcja rodowodu cukrzycy",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Wiek pacjenta w latach", verbose_name="Wiek"
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        help_text="Prawdopodobieństwo cukrzycy (0.0 - 1.0)",
                        verbose_name="Prawdopodobieństwo",
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        help_text="Prawdopodobieństwo w procentach",
                        verbose_name="Procent",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("niskie", "Niskie"),
                            ("umiarkowane", "Umiarkowane"),
                            ("wysokie", "Wysokie"),
                            ("bardzo wysokie", "Bardzo wysokie"),
                        ],
                        max_length=20,
                        verbose_name="Poziom ryzyka",
                    ),
                ),
                (
                    "risk_color",
                    models.CharField(
                        help_text="Kolor dla wizualizacji (green, yellow, orange, red)",
                        max_length=10,
                        verbose_name="Kolor ryzyka",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diabetes_prediction",
                        to="appointments.appointment",
                        verbose_name="Wizyta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctors.doctor",
                        verbose_name="Utworzone przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predykcja cukrzycy",
                "verbose_name_plural": "Predykcje cukrzycy",
                "ordering": ["-created_at"],
            },
        ),
    ]
