# Generated by Django 5.2.6 on 2025-09-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_cancellation_time',
            field=models.DateTimeField(blank=True, help_text='Czas ostatniego anulowania wizyty', null=True),
        ),
    ]
