# Generated by Django 5.2.6 on 2025-10-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_last_cancellation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diabetes_type',
            field=models.CharField(choices=[('healthy', 'Zdrowy'), ('type1', 'Cukrzyca typu 1'), ('type2', 'Cukrzyca typu 2'), ('gestational', 'Cukrzyca ciążowa')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
