# Generated by Django 5.2.7 on 2025-10-29 12:25

import utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patient_diabetes_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="pesel",
            field=models.CharField(
                help_text="Numer PESEL (11 cyfr z poprawną sumą kontrolną)",
                max_length=11,
                unique=True,
                validators=[utilities.validators.PESELValidator()],
            ),
        ),
    ]
