# Generated by Django 5.2.6 on 2025-09-10 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(choices=[('endocrinologist', 'Endokrynolog'), ('diabetologist', 'Diabetolog'), ('internal_medicine', 'Internista'), ('family_medicine', 'Lekarz rodzinny')], max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('office_address', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('working_days', models.CharField(choices=[('mon-fri', 'Poniedziałek-Piątek'), ('mon-sat', 'Poniedziałek-Sobota'), ('tue-thu', 'Wtorek-Czwartek')], default='mon-fri', max_length=20)),
                ('education', models.TextField()),
                ('certifications', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
            },
        ),
    ]
